### ISSUE TITLE
IndexError when activating the normalization of the angles

### ISSUE THREAD

**Issue by Sebastien-PILUSO** [PolarBean/DeepSlice#35]
Hi, I activated the `propagate_angles` option using the basic example you posted on this git repo, but whatever the number of slices I have in my input folder, I always get an `IndexError` such as:
`Traceback (most recent call last):
  File "deepslice.py", line 13, in <module>
    Model.propagate_angles() 
  File "/home/piluso/miniconda3/envs/deepslice/lib/python3.7/site-packages/DeepSlice/main.py", line 131, in propagate_angles
    self.predictions, method, self.species
  File "/home/piluso/miniconda3/envs/deepslice/lib/python3.7/site-packages/DeepSlice/coord_post_processing/angle_methods.py", line 112, in propagate_angles
    DV_angle_list, ML_angle_list, method, depths, species
  File "/home/piluso/miniconda3/envs/deepslice/lib/python3.7/site-packages/DeepSlice/coord_post_processing/angle_methods.py", line 88, in get_mean_angle
    weighted_accuracy = [weighted_accuracy[int(y)] for y in df_center]
  File "/home/piluso/miniconda3/envs/deepslice/lib/python3.7/site-packages/DeepSlice/coord_post_processing/angle_methods.py", line 88, in <listcomp>
    weighted_accuracy = [weighted_accuracy[int(y)] for y in df_center]
IndexError: index 529 is out of bounds for axis 0 with size 528
`
Could you please help me solving this issue?

**Comment by PolarBean** [comment]
Funnily enough I just patched this on the development brach. I have merged this into main now and created a new release on PyPi. https://pypi.org/project/DeepSlice/ Update DeepSlice from wherever you installed it and the problem should be fixed. Let me know how you go! :)

**Comment by PolarBean** [comment]
closing for now but feel free to reopen if you're issue is unsolved.

**Comment by Sebastien-PILUSO** [comment]
You did well, I updated the code and it worked, many thanks!
