### ISSUE TITLE
No such file error Deepslice_cli_v1.1.5.1.py 

### ISSUE THREAD

**Issue by Sarruedi** [PolarBean/DeepSlice#49]
I'm trying to run Deepslice in combination with the GUI of ABBA. When loading sections I get the following error. 
Can anyone advise on how to add the deepslice_cli_v1.1.5.1.py file as it's not contained in the downloaded files? 

java.nio.file.NoSuchFileException: C:\Users\username\.conda\envs\deepslice\deepslice_cli_v1.1.5.1.py
	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:79)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.newByteChannel(WindowsFileSystemProvider.java:230)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.copy(Files.java:3016)
	at ch.epfl.biop.wrappers.deepslice.DeepSlice.ensureScriptIsCopied(DeepSlice.java:77)
	at ch.epfl.biop.wrappers.deepslice.DeepSlice.execute(DeepSlice.java:90)
	at ch.epfl.biop.wrappers.deepslice.DeepSlice.execute(DeepSlice.java:177)
	at ch.epfl.biop.wrappers.BiopWrappersCheck.isDeepSliceSet(BiopWrappersCheck.java:70)
	at ch.epfl.biop.wrappers.deepslice.ij2commands.DeepSlicePrefsSet.run(DeepSlicePrefsSet.java:36)
	at org.scijava.command.CommandModule.run(CommandModule.java:196)
	at org.scijava.module.ModuleRunner.run(ModuleRunner.java:165)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:125)
	at org.scijava.module.ModuleRunner.call(ModuleRunner.java:64)
	at org.scijava.thread.DefaultThreadService.lambda$wrap$2(DefaultThreadService.java:247)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Could not copy CLI script: C:\Users\username\.conda\envs\deepslice\deepslice_cli_v1.1.5.1.py
Please try to add the script file manually
The CLI script to DeepSlice could not be copied to the env folder (C:\Users\username\.conda\envs\deepslice)
You can try to copy manually deepslice_cli_v1.1.5.1.py to this folder

**Comment by PolarBean** [comment]
Hey, this seems to have been resolved in the following ABBA issue https://github.com/BIOP/ijp-imagetoatlas/issues/191
Don't hesitate to reopen if the problem persists!

all the best, 

Harry
